version: "3"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: data

  app:
    image: my-node-app
    ports:
      - 13000:3000
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "adminer_data:/data"

volumes:
  adminer_data:
    driver: local